### ISSUE TITLE
update, maybe?

### ISSUE THREAD

**Issue by AndreasYNY** [Hazuki-san/osu-redo#1]
it's been couple of days since the client is not working i still think it because of updates....
![image](https://user-images.githubusercontent.com/46004308/96869092-34018a00-1499-11eb-8eca-b06c793296d5.png)
or it's just my laptop 🤔

**Comment by Hazuki-san** [comment]
because osu!auth.dll got updated, and my laptop is currently dead right now... I cannot work on client until I get my laptop fixed. Sorry about that!

**Comment by AndreasYNY** [comment]
got it! i will wait!

**Comment by Hazuki-san** [comment]
updated for you in commit 11d3d3eb6f1bb8f7f815aba631edcfb5bb9b10e1
