### ISSUE TITLE
stable b20201126 outdated

### ISSUE THREAD

**Issue by areuokmanyeahthanksnoproblem** [Hazuki-san/osu-redo#2]
Unable to login through osu!Redo, outdated client :(

![screenshot001](https://user-images.githubusercontent.com/81771177/113333523-126ecd80-936a-11eb-894c-a6b20217bc1d.jpg)

**Comment by Hazuki-san** [comment]
Thank you for reporting! I'll update it soon!

**Comment by Hazuki-san** [comment]
update done! have fun!
