### ISSUE TITLE
UninstallID key not found

### ISSUE THREAD

**Issue by shanty443** [Hazuki-san/osu-redo#3]
![image](https://user-images.githubusercontent.com/82418727/115803960-dd3e2400-a3d9-11eb-9032-5bae94ed0148.png)

**Comment by Hazuki-san** [comment]
You're either "haven't install osu! yet" or you modified the UninstallID by using third parties tools. Try reinstall osu! again.

**Comment by SpookerI** [comment]
If the reinstalling osu! not helped please delete your uninstallid manually:
1. Open run window and type "regedit" in it.
2. When regedit opens go to this path: \HKEY_CURRENT_USER\Software\osu!
3. Delete UninstallID
