### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by PeppyAssEater** [Hazuki-san/osu-redo#5]
ass

**Comment by Hazuki-san** [comment]
it should be working fine, isn't it?

**Comment by PeppyAssEater** [comment]
> it should be working fine, isn't it?

its just updating, and i cannot find teh device spoofer setting

**Comment by PeppyAssEater** [comment]
replaced osu! .exe, crashes

**Comment by Hazuki-san** [comment]
alright, new update will be there soon.

**Comment by Hazuki-san** [comment]
pushed @PeppyAssEater https://github.com/Hazuki-san/osu-redo/commit/2beb89f17518420941ed8429a4aa813d969d0443
