### ISSUE TITLE
dick

### ISSUE THREAD

**Issue by PeppyAssEater** [Hazuki-san/osu-redo#6]
[runtime.log](https://github.com/Hazuki-san/osu-redo/files/6920266/runtime.log)
[update.log](https://github.com/Hazuki-san/osu-redo/files/6920267/update.log)

**Comment by Hazuki-san** [comment]
No error? Is there something wrong?

**Comment by PeppyAssEater** [comment]
internet = crash and osu requesting update
without internet = 5 sec then osu closes and requesting update

**Comment by PeppyAssEater** [comment]
![image](https://user-images.githubusercontent.com/87293291/127977780-9214c07b-2dff-40d8-a050-20e5c2360977.png)

**Comment by PeppyAssEater** [comment]
dont look at the name of path, im used fallback to update to latest version

**Comment by Hazuki-san** [comment]
try to open osu!.cfg and change `_AHC = 1` to `_AHC = 0`

**Comment by PeppyAssEater** [comment]
still requesting update

**Comment by Hazuki-san** [comment]
open normal game and exit then open redo

**Comment by Hazuki-san** [comment]
or delete `.require_update`

**Comment by PeppyAssEater** [comment]
still crashing

**Comment by Hazuki-san** [comment]
runtime.log doesn't have error?

**Comment by Hazuki-san** [comment]
Are you running on Windows 11?

**Comment by PeppyAssEater** [comment]
im running on windows 8.1

**Comment by Hazuki-san** [comment]
Have you tried compatibility mode as Windows 7?

**Comment by PeppyAssEater** [comment]
still crashing

**Comment by Hazuki-san** [comment]
Is it crashing at "welcome" screen?

**Comment by PeppyAssEater** [comment]
yes

**Comment by Hazuki-san** [comment]
OK, I'll push safe-mode exe for it later (No AHC). Expect an update soon.
